<?php

namespace Utils\URL;

require_once dirname(__FILE__) . '/../../../Utils/URL/Url.inc';

/**
 * Test class for Url.
 * Generated by PHPUnit on 2011-10-10 at 20:43:20.
 */
class UrlTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Url
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Url('http', 'localhost', '/path/to/file.php', 8080);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     */
    public function testGetProtocol()
    {
        $this->assertEquals('http', $this->object->getProtocol());
    }

    /**
     */
    public function testGetHost()
    {
        $this->assertEquals('localhost', $this->object->getHost());
    }

    /**
     * @todo Implement testGetPath().
     */
    public function testGetPath()
    {
        $this->assertEquals('/path/to/file.php', $this->object->getPath());
    }

    /**
     * @todo Implement testGetPort().
     */
    public function testGetPort()
    {
        $this->assertEquals(8080, $this->object->getPort());
    }

    /**
     * @todo Implement testSetPath().
     */
    public function testSetPath()
    {
        $this->object = $this->object->setPath('/new/path/to/new/file.html');

        $this->assertEquals('/new/path/to/new/file.html', $this->object->getPath());
    }

    /**
     * @todo Implement test__toString().
     */
    public function test__toString()
    {
        $this->assertEquals('http://localhost:8080/path/to/file.php', $this->object->__toString());
    }
}